### ISSUE TITLE
Failure compiling Ruby

### ISSUE THREAD

**Issue by devcamcar** [cf-platform-eng/mesos-boshrelease#2]
Hi all, this looks really promising and I've been wanting to test drive it. I am running this in an OpenStack / KVM environment with a recent Trusty stemcell (bosh-openstack-kvm-ubuntu-trusty-go_agent v2840).

I am currently running into a compilation issue with Ruby:

https://gist.github.com/devcamcar/03f3ec8b4fee4cdec55e

I am curious which stemcell you are using?  I also tried a Lucid stemcell with the same result.

Thanks!

**Comment by ipolyzos** [comment]
I have the same issue both in warden and AWS stemcells v2840. Your advice would be very appreciated.

Thanks

**Comment by frodenas** [comment]
When I tested and cut the release I used a 2479 bosh stemcell. That stemcell had libyaml installed by default, but later stemcells dropped it (see commit https://github.com/cloudfoundry/bosh/commit/9e63d128dce0186f8bb23cdc4a13493b0108c277#diff-9b2773a8b14a55ca37b03dfe5e34a854L56). 

The fix is already in the master of this repo, when compiling ruby you just need to compile the libyaml library (see commit https://github.com/cf-platform-eng/mesos-boshrelease/commit/c37855ca504a16a420477731c19b299959c654ac#diff-dd3a91430f204c303b0af44d4d4ec03eR37). But I didn't had time to finish my tests, IIRC there's still a problem when registering frameworks. I'll try to cut a new release with the fix during the next weeks.

Another option if you had a chance is to use an old stemcell with libyaml.

**Comment by devcamcar** [comment]
Using 2479 worked for me, thanks!

**Comment by ipolyzos** [comment]
I would like to confirm also that 2479 for me as well in OpenStack however not in AWS

**Comment by poblin-orange** [comment]
hello,
met this issue with openstack kvm 2922 stemcell. Is using an old stemcell the only option ?

**Comment by frodenas** [comment]
@poblin-orange Unfortunately yes.

**Comment by frodenas** [comment]
I've created a new [Mesos Bosh release v2](https://github.com/cf-platform-eng/mesos-boshrelease/releases/tag/v2) that work with the latests stemcells.

**Comment by poblin-orange** [comment]
thank you @frodenas :-) !
