### ISSUE TITLE
gethostbyname2: Unknown host

### ISSUE THREAD

**Issue by ipolyzos** [cf-platform-eng/mesos-boshrelease#3]
Hi all, 

 I have an issue deploying to a clean new openstack environment. Deployment of mesos-master vm produce a "gethostbyname2: Unknown host" error.

 Exploring the logs i see the following entry in mesos-master.stderr.log 
 
> *** Check failure stack trace: ***
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> F0316 17:37:56.008083 14837 process.cpp:1471] Failed to initialize, gethostbyname2: Unknown host

It seems that this is well known problem to mesos deployments and can be traced at mesos mailing list  @ http://www.mail-archive.com/search?q=gethostbyname2&l=user%40mesos.apache.org. 
  
I was wondering if would be possible to pass ip through the "--ip" or hostname "--hostname" during run.

**Comment by ipolyzos** [comment]
I can see in the ctl scripts that ip and port are configured, something that cover the resolution given in the mailing list I have attached in the initial comment.

**Comment by ipolyzos** [comment]
Problem solved. This was caused due to the /etc/hosts values/. SSHing into the master node and configure accordingly solves the problem.

**Comment by frodenas** [comment]
That's interesting. What hostname did you finally configure at the hosts file?

Theoretically, the hostname is set at the [control script](https://github.com/cf-platform-eng/mesos-boshrelease/blob/master/jobs/mesos-master/templates/bin/mesos_master_ctl.erb#L9). For OpenStack it should be the hostname assigned by BOSH. So what might be happen is that the hostname is unresolvable because there isn't any dns address at the resolv.conf file pointing to the BOSH DNS server. Can you please check if this is true on your environment?

**Comment by ipolyzos** [comment]
Indeed this true for my environment. What I use through as a temporary fix is to manually add to _/etc/hosts_ file an entry mapping the _public_hostname_ to the _listen_ip_.  It would be nice if this could be part of the control script and run once upon provisioning of the service. 

Expressing the temp solution to a script running on master nodes could be :

>#!/bin/bash
>
>mhn=$(hostname)
>mip=$(/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
>
>sed -i "1 i $mip $mhn" /etc/hosts

**Comment by frodenas** [comment]
This should be solved at [Mesos Bosh release v2](https://github.com/cf-platform-eng/mesos-boshrelease/releases/tag/v2). Please reopen if you still face the same problem.
